/** Sherlock/Maigret-class public profile URL templates (existence probes only). */
export interface SherlockSite {
  platform: string;
  url: (username: string) => string;
  /** api = use dedicated resolver elsewhere; head = HTTP GET probe */
  method: "head" | "get";
}

export const SHERLOCK_SITES: SherlockSite[] = [
  { platform: "GitLab", url: (u) => `https://gitlab.com/${u}`, method: "head" },
  { platform: "Medium", url: (u) => `https://medium.com/@${u}`, method: "head" },
  { platform: "SoundCloud", url: (u) => `https://soundcloud.com/${u}`, method: "head" },
  { platform: "Bandcamp", url: (u) => `https://${u}.bandcamp.com`, method: "head" },
  { platform: "YouTube", url: (u) => `https://www.youtube.com/@${u}`, method: "head" },
  { platform: "Docker Hub", url: (u) => `https://hub.docker.com/u/${u}`, method: "head" },
  { platform: "npm", url: (u) => `https://www.npmjs.com/~${u}`, method: "head" },
  { platform: "Pastebin", url: (u) => `https://pastebin.com/u/${u}`, method: "head" },
  { platform: "Pinterest", url: (u) => `https://www.pinterest.com/${u}/`, method: "head" },
  { platform: "Instagram", url: (u) => `https://www.instagram.com/${u}/`, method: "head" },
  { platform: "TikTok", url: (u) => `https://www.tiktok.com/@${u}`, method: "head" },
  { platform: "Imgur", url: (u) => `https://imgur.com/user/${u}`, method: "head" },
  { platform: "Letterboxd", url: (u) => `https://letterboxd.com/${u}/`, method: "head" },
  { platform: "TryHackMe", url: (u) => `https://tryhackme.com/p/${u}`, method: "head" },
  { platform: "Telegram", url: (u) => `https://t.me/${u}`, method: "head" },
  { platform: "Archive.org", url: (u) => `https://archive.org/details/@${u}`, method: "head" },
  { platform: "Spotify", url: (u) => `https://open.spotify.com/user/${u}`, method: "head" },
  { platform: "Hubski", url: (u) => `https://hubski.com/user/${u}`, method: "head" },
  { platform: "Slashdot", url: (u) => `https://slashdot.org/~${u}`, method: "head" },
  { platform: "BoardGameGeek", url: (u) => `https://boardgamegeek.com/user/${u}`, method: "head" },
  { platform: "BugCrowd", url: (u) => `https://bugcrowd.com/${u}`, method: "head" },
  { platform: "GeeksforGeeks", url: (u) => `https://auth.geeksforgeeks.org/user/${u}`, method: "head" },
  { platform: "Giphy", url: (u) => `https://giphy.com/${u}`, method: "head" },
  { platform: "HackenProof", url: (u) => `https://hackenproof.com/hackers/${u}`, method: "head" },
  { platform: "LibraryThing", url: (u) => `https://www.librarything.com/profile/${u}`, method: "head" },
  { platform: "Lobsters", url: (u) => `https://lobste.rs/u/${u}`, method: "head" },
  { platform: "Smule", url: (u) => `https://www.smule.com/${u}`, method: "head" },
  { platform: "Splice", url: (u) => `https://splice.com/${u}`, method: "head" },
  { platform: "Weblate", url: (u) => `https://hosted.weblate.org/user/${u}/`, method: "head" },
  { platform: "About.me", url: (u) => `https://about.me/${u}`, method: "head" },
  { platform: "Behance", url: (u) => `https://www.behance.net/${u}`, method: "head" },
  { platform: "Dribbble", url: (u) => `https://dribbble.com/${u}`, method: "head" },
  { platform: "Flickr", url: (u) => `https://www.flickr.com/people/${u}/`, method: "head" },
  { platform: "Gravatar Profile", url: (u) => `https://en.gravatar.com/${u}`, method: "head" },
  { platform: "Hackaday", url: (u) => `https://hackaday.io/${u}`, method: "head" },
  { platform: "Instructables", url: (u) => `https://www.instructables.com/member/${u}/`, method: "head" },
  { platform: "Kaggle", url: (u) => `https://www.kaggle.com/${u}`, method: "head" },
  { platform: "Mastodon.social", url: (u) => `https://mastodon.social/@${u}`, method: "head" },
  { platform: "MyAnimeList", url: (u) => `https://myanimelist.net/profile/${u}`, method: "head" },
  { platform: "Replit", url: (u) => `https://replit.com/@${u}`, method: "head" },
  { platform: "Roblox", url: (u) => `https://www.roblox.com/user.aspx?username=${u}`, method: "head" },
  { platform: "Snapchat", url: (u) => `https://www.snapchat.com/add/${u}`, method: "head" },
  { platform: "Steam (vanity)", url: (u) => `https://steamcommunity.com/id/${u}`, method: "head" },
  { platform: "Trello", url: (u) => `https://trello.com/${u}`, method: "head" },
  { platform: "Venmo", url: (u) => `https://venmo.com/u/${u}`, method: "head" },
  { platform: "Vimeo", url: (u) => `https://vimeo.com/${u}`, method: "head" },
  { platform: "Wattpad", url: (u) => `https://www.wattpad.com/user/${u}`, method: "head" },
  { platform: "WordPress", url: (u) => `https://${u}.wordpress.com`, method: "head" },
  { platform: "Cash App", url: (u) => `https://cash.app/$${u}`, method: "head" },
  { platform: "Codecademy", url: (u) => `https://www.codecademy.com/profiles/${u}`, method: "head" },
  { platform: "Freelancer", url: (u) => `https://www.freelancer.com/u/${u}`, method: "head" },
  { platform: "Gumroad", url: (u) => `https://${u}.gumroad.com/`, method: "head" },
  { platform: "Patreon", url: (u) => `https://www.patreon.com/${u}`, method: "head" },
  { platform: "Product Hunt", url: (u) => `https://www.producthunt.com/@${u}`, method: "head" },
  { platform: "Sketchfab", url: (u) => `https://sketchfab.com/${u}`, method: "head" },
  { platform: "TradingView", url: (u) => `https://www.tradingview.com/u/${u}/`, method: "head" },
  { platform: "Unsplash", url: (u) => `https://unsplash.com/@${u}`, method: "head" },
];